-- Create raw table for storing job API responses

CREATE TABLE IF NOT EXISTS JOB_DB.RAW.RAW_JOBS_API (
    FILENAME STRING,
    SOURCE_INGEST_TIMESTAMP TIMESTAMP_TZ,
    SNOWFLAKE_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_DATA VARIANT
);