-- Create Snowpipe for automatic ingestion from Amazon S3

CREATE PIPE IF NOT EXISTS JOB_DB.RAW.JOB_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO JOB_DB.RAW.RAW_JOBS_API
(
    FILENAME,
    SOURCE_INGEST_TIMESTAMP,
    RAW_DATA
)
FROM
(
    SELECT
        METADATA$FILENAME,
        $1:metadata.source_ingest_timestamp::TIMESTAMP_TZ,
        $1
    FROM @JOB_DB.RAW.JOB_EXTSTAGE
)
FILE_FORMAT = (
    FORMAT_NAME = JOB_DB.RAW.JSON_FORMAT
);